global using System.Collections.ObjectModel;
global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Styling;
global using Biz.Shell;
global using Biz.Shell.ViewModels;
global using Biz.Modules.Dashboard.ViewModels;
global using Biz.Modules.Dashboard.Views;
global using Biz.Shell.Services;